# Site settings
title: Comi 曦方
SEOTitle: Comi 曦方
header-img: img/home.webp
email: comi@disroot.org
description: "这里是 @Comi曦方 的个人博客"
keyword: "左翼,翻译,文章,Communism,Maoist,Soviet,Marxism"
url: "https://comi.nets.hk" # your host, for absolute URL 
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: null
zhihu_username: comi-91-30
# github_username: null
# twitter_username: null
#facebook_username:  null
#linkedin_username:  firstname-lastname-idxxxx
bilibili_username: 2092779975 #your_bilibili_id

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: COMI

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: comi.nets.hk

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "打酱油ing <br> comi@disroot.org"
sidebar-avatar: https://i.postimg.cc/nrGRqfwW/head.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#F7EED6"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  - title: "远方来信"
    href: "https://www.zhihu.com/people/yuanfanglaixin"
  - title: "红色影像及实践"
    href: "https://space.bilibili.com/451414993/"
  - title: "红色威丁"
    href: "https://space.bilibili.com/14012168/"
  - title: "Kasamang Rino"
    href: "https://space.bilibili.com/3546583746481059/"
  - title: "解读资本论"
    href: "https://space.bilibili.com/381656061/"